### ISSUE TITLE
Sub-sampling paired-end reads

### ISSUE THREAD

**Issue by Midnighter** [yuifu/FastqSubsample#1]
I realize that you haven't worked on this tool in a long time and probably moved on to other things.

However, I was curious what you think about sub-sampling paired-end reads? These usually data come in separate files `x_1.fastq` and `x_2.fastq` so if I applied your program separately different reads would be selected breaking the pairs, as far as I understand.

Thanks for any ideas.

**Comment by Midnighter** [comment]
Apparently, the way that `seqtk` handles this, for example, is by using the same seed for each pair file. I guess the same would work here?

**Comment by yuifu** [comment]
Sorry for my late reply. Thank you for asking.

> by using the same seed for each pair file

That's right!

**Comment by Midnighter** [comment]
Thanks for confirming. 🙂
